import PDFDocument from 'pdfkit';
import { Report } from '../models/Report';

export class PDFGenerator {
    generateReportPDF(report: Report): PDFKit.PDFDocument {
        const doc = new PDFDocument({ margin: 50 });

        // Header
        doc
            .fontSize(20)
            .text('InfraCost Analyzer Pro', { align: 'center' })
            .moveDown();

        doc
            .fontSize(16)
            .text('Cost Report', { align: 'center' })
            .moveDown();

        // Report details
        doc
            .fontSize(12)
            .text(`Report Name: \${report.name}`)
            .text(`Type: \${report.type}`)
            .text(`Generated: \${report.createdAt.toLocaleString()}`)
            .text(`Total Monthly Cost: \$\${report.totalMonthlyCost}`)
            .moveDown();

        // Divider
        doc
            .moveTo(50, doc.y)
            .lineTo(550, doc.y)
            .stroke()
            .moveDown();

        // Data section
        doc.fontSize(14).text('Cost Breakdown', { underline: true }).moveDown();

        if (report.type === 'terraform') {
            this.addTerraformDetails(doc, report.data);
        } else if (report.type === 'aws_calculator') {
            this.addAWSCalculatorDetails(doc, report.data);
        }

        // Footer
        doc
            .moveDown()
            .fontSize(10)
            .text(
                'Generated by InfraCost Analyzer Pro',
                { align: 'center' }
            );

        return doc;
    }

    private addTerraformDetails(doc: PDFKit.PDFDocument, data: any) {
        doc.fontSize(11);

        if (data.resources) {
            doc.text('Resources:', { underline: true }).moveDown(0.5);

            data.resources.slice(0, 20).forEach((resource: any) =& gt; {
                doc
                    .text(`• \${resource.name} (\${resource.type})`)
                    .text(`  Monthly Cost: \$\${resource.monthlyCost}`, { indent: 20 })
                    .moveDown(0.5);
            });
        }

        if (data.summary) {
            doc.moveDown().text('Summary:', { underline: true }).moveDown(0.5);
            doc.text(`Total Resources: \${data.summary.totalResources}`);

            if (data.summary.costByService) {
                doc.text('Cost by Service:');
                Object.entries(data.summary.costByService).forEach(([service, cost]) =& gt; {
                    doc.text(`  \${service}: \$\${cost}`, { indent: 20 });
                });
            }
        }
    }

    private addAWSCalculatorDetails(doc: PDFKit.PDFDocument, data: any) {
        doc.fontSize(11);

        if (data.instanceCost) {
            doc.text('Instance Cost:', { underline: true }).moveDown(0.5);
            doc.text(`Hourly: \$\${data.instanceCost.hourly}`);
            doc.text(`Monthly: \$\${data.instanceCost.monthly}`);
            doc.moveDown();
        }

        if (data.breakdown) {
            doc.text('Configuration:', { underline: true }).moveDown(0.5);
            Object.entries(data.breakdown).forEach(([key, value]) =& gt; {
                doc.text(`\${key}: \${value}`);
            });
        }
    }
}

export const pdfGenerator = new PDFGenerator();