'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Sparkles, Lightbulb, FileText, MessageCircle } from 'lucide-react';

export default function AiAssistant() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('complete');

  const handleAICall = async () => {
    if (!input.trim()) return;
    
    setIsLoading(true);
    
    // In a real app, this would call the backend AI API
    // For now, we'll simulate the response
    setTimeout(() => {
      const mockResponses = {
        complete: `Here's a detailed response to: "${input}". This is a simulated AI response that would normally be generated by the AI service based on your input.`,
        summarize: input.length > 50 ? `${input.substring(0, 50)}...` : input,
        suggest: `Based on your project context, here are some suggested tasks:\n- Implement authentication module\n- Create project dashboard\n- Design task management system`,
        name: 'AI-Generated Project Name',
      };
      
      setOutput(mockResponses[activeTab as keyof typeof mockResponses] || '');
      setIsLoading(false);
    }, 1000);
  };

  const getTabInfo = () => {
    switch (activeTab) {
      case 'complete':
        return { title: 'Text Completion', icon: <Sparkles className="h-4 w-4" />, placeholder: 'Enter text to complete or expand...' };
      case 'summarize':
        return { title: 'Summarize', icon: <FileText className="h-4 w-4" />, placeholder: 'Enter text to summarize...' };
      case 'suggest':
        return { title: 'Task Suggestions', icon: <Lightbulb className="h-4 w-4" />, placeholder: 'Describe your project to get task suggestions...' };
      case 'name':
        return { title: 'Project Name', icon: <MessageCircle className="h-4 w-4" />, placeholder: 'Describe your project to generate a name...' };
      default:
        return { title: 'AI Assistant', icon: <Sparkles className="h-4 w-4" />, placeholder: 'Enter your request...' };
    }
  };

  const tabInfo = getTabInfo();

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>AI Assistant</CardTitle>
          <div className="flex space-x-2">
            <Button
              variant={activeTab === 'complete' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setActiveTab('complete')}
            >
              <Sparkles className="h-4 w-4 mr-1" />
              Complete
            </Button>
            <Button
              variant={activeTab === 'summarize' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setActiveTab('summarize')}
            >
              <FileText className="h-4 w-4 mr-1" />
              Summarize
            </Button>
            <Button
              variant={activeTab === 'suggest' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setActiveTab('suggest')}
            >
              <Lightbulb className="h-4 w-4 mr-1" />
              Suggest
            </Button>
            <Button
              variant={activeTab === 'name' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setActiveTab('name')}
            >
              <MessageCircle className="h-4 w-4 mr-1" />
              Name
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <Badge variant="secondary" className="text-xs">
              {tabInfo.icon}
              {tabInfo.title}
            </Badge>
          </div>
          
          <Textarea
            placeholder={tabInfo.placeholder}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            rows={4}
          />
          
          <div className="flex justify-between items-center">
            <p className="text-sm text-gray-500">
              {input.length}/500 characters
            </p>
            <Button 
              onClick={handleAICall} 
              disabled={isLoading || !input.trim()}
            >
              {isLoading ? (
                <div className="flex items-center">
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Processing...
                </div>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  Generate
                </>
              )}
            </Button>
          </div>
          
          {output && (
            <div className="mt-4 p-4 bg-gray-50 rounded-lg">
              <h4 className="font-medium mb-2">AI Response:</h4>
              <p className="whitespace-pre-line">{output}</p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}